# LATIHAN KONVERSI SATUAN TEMPERATURE

print("\nPROGRAM KONVERSI TEMPERATUR\n")

celcius = float(input("masukan suhu dalam celcius = "))
print ("suhu adalah", celcius , "Celcius")

#reamur
reamur = (4/5) * celcius
print ("suhu dalam reamur adalah = ",reamur, "reamur")

#fahrenheit
fahrenheit = ((9/5) * celcius) + 32
print ("suhu dalam reamur adalah = ",fahrenheit, "Fahrenheit")

kelvin = celcius + 273
print ("suhu dalam reamur adalah = ",kelvin, "Kelvin")
